### ISSUE TITLE
Model File Download Link Issue

### ISSUE THREAD

**Issue by utd-simlab** [chail/anyres-gan#9]
Hey first thank you so much for releasing this work with all of the code, very impressive! I'm trying to download the pretrained models using the `download_resources.sh` script. However, I'm running into an issue where the model file seems to be missing or removed from the server, am I trying the right [URL](https://latent-composition.csail.mit.edu/other_projects/anyres_gan/pretrained/ffhq6k_pretrained_final.pkl)?

Thanks again!

**Comment by chail** [comment]
Sorry about that, I think the URL should work now!
